Vagrant.configure(2) do |config|
  config.vm.provider 'virtualbox'
  config.vm.box = 'ubuntu/xenial64'

  config.vm.provider :virtualbox do |vb|
    vb.name = 'ist-652-hw2'
  end

  config.vm.provision 'shell', inline: <<-SHELL
    ## install mongo + pymongo
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
    echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
    apt-get update
    apt-get install -y python3-pip mongodb-org
    pip3 install pymongo

    ## start mongodb
    mkdir -p /data/db
    mongod --fork --logpath /var/log/mongod.log --dbpath /data/db

    ## consume data
    cd /vagrant
    python3 run.py consume
  SHELL
end